### ISSUE TITLE
Cant Disable Secondary Password

### ISSUE THREAD

**Issue by tiosolid** [blockchain/My-Wallet#12]
After Enabling Secondary Password, it cant be disabled anymore.

Steps to Reproduce the Problem:
1. Login into My Wallet > Passwords > Enable Secondary Password;
2. Type in the desired password and wait for the browser to finish the criptografic process;
3. Click the button to disable the secondary password;
4. The "canvas" shows a error message (red box) saying "Password must be 4 characters or more in length", but no box to type it (or modal) is shown.

If you logoff,login again and repeat the steps 1-3 (but for disabling the secondary password), the modal window with the virtual keyboard is now shown, but:
- if you type the WRONG secondary password, nothing happens (as expected);
- if you type the CORRECT secondary password, the password mnemonic frame is expanded (meaning that the password was received) but if you go and click the "disable secondary password" button again, the red error box is shown and nothing else happens;

Environment:
- Windows 7 Professional
- Firefox 18.0.1 - Everything javascript related enabled

Attached to this issue report is a screenshot showing the exact error:
![Capture](https://f.cloud.github.com/assets/251017/92394/323c420a-65ce-11e2-8ff1-20df8313e602.JPG)

Bounty: 1GQwoEwV6J7QNdgxQJV6do2Nmyd2NhbM6K

**Comment by iraqitelecom** [comment]
Lost double encryption password on blockchain.info, now what? help me

**Comment by dscotese** [comment]
IraqiTelecom, this isn't the place to request support, but as far as I know you have two options:
1. Give up and consider the funds in the wallet to be lost (if it helps, you've lowered the supply of bitcoin which enriches everyone who holds bitcoin).
2. Start a brute-force search to find your secondary password.

**Comment by johnjames333** [comment]
@tiosolid 
@iraqitelecom 
@dscotese 
we have developed our own hardware for cracking all versions of blockchain wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333 or gmail : walletsrecoveryservice@gmail.com

**Comment by mattpattersun** [comment]
@iraqitelecom 
I have a very efficient method for recovering double encryption password of blockchain wallet. and the safest part is that, I don't ask for anything from you I just guide you through the steps to get access to your wallet. and if successful I ask to offer me 20% of your balance. so if you want help to get your lost secondary password, send me email: 
anywalletrecovery@gmail.com

**Comment by DanielsBerlin** [comment]
@iraqitelecom 
I know a way you can login to your account
I had similar issue I solved it
