### ISSUE TITLE
export list of addresses for account

### ISSUE THREAD

**Issue by jangorecki** [blockchain/My-Wallet#125]
Feature request.
Would be nice to have easy way to export addresses for account without enabling api or revealing private keys. See [this stackexchange](http://bitcoin.stackexchange.com/questions/40582/export-a-list-of-addresses-associated-to-blockchain-info-account/40588#comment46683_40588).

**Comment by MuhammedZakir** [comment]
I think adding a secondary password maybe a good idea. We can append that password to API to access the account. When using it, only public keys(or addresses) will be released. It will be secure. At the best, a hacked can only extract all the public keys. Opinions?

**Comment by jangorecki** [comment]
Seems reasonable, but for non-merchants, but simple user who wants to manage multiple addresses just a simply button for popup with `addr1\naddr2\naddr3` to copy-paste it would be well enough.

**Comment by MuhammedZakir** [comment]
API can be used by everyone. However, for easiness, an option in wallet is better. There is already a export to PDF option. After clicking it, wallet can ask whether to export addresses plus private keys or just addresses plus public keys. But, if the user export list of addresses(and/or public keys) frequently, its better to use an API, something like I mentioned. I am for adding both! Hope we can hear from developers.

**Comment by tuzzolo** [comment]
Hey guys. Thanks for the suggestions. Better place to FRs would be over here: https://github.com/blockchain/my-wallet-v3-frontend.

**Comment by jangorecki** [comment]
@tuzzolo done, closing this one

**Comment by Sjors** [comment]
Keep in mind though that My Wallet V3 Frontend is a completely revamped wallet (see https://alpha.blockchain.info), so please try it out before filing a feature request. Depending on when you read this, you may need to get an invite code [here](https://www.blockchain.com/invite/).
