### ISSUE TITLE
Recovering a 21-word mneumonic

### ISSUE THREAD

**Issue by kennsippell** [blockchain/My-Wallet#143]
A friend came to me with a seed for a wallet she made on blockchain.info back in 2013. She has a photo of a 21 word recovery seed containing some super-weird words like `graf`. Doesn't seem to be BIP or Electrum -- wondering if you guys used your own seeding algorithm back in those days maybe? Or if you'd have any helpful tips for recovering the wallet. https://ibb.co/n0NyH6

**Comment by mpfluger** [comment]
We did have a mnemonic back in the day to recover your guid and password. Please use the following page to recover a wallet from a legacy mnemonic:

https://blockchain.info/wallet/recover-wallet

**Comment by kennsippell** [comment]
@mpfluger Thanks for the pointer! I've tried this but dead-end at "Please check your email to approve this login attempt." Is it possible to recover the wallet without knowledge of the email that was used to set up the wallet?

**Comment by mpfluger** [comment]
Please check with support, they should be able to help:

https://support.blockchain.com/hc/en-us/requests/new

**Comment by johnjames333** [comment]
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022

**Comment by matthew202020** [comment]
@kennsippell did you manage to restore your blockchain wallet problem, If not I can recover it for you, contact me: [[anywalletrecovery@gmail.com]
