### ISSUE TITLE
Import wallet.dat not working

### ISSUE THREAD

**Issue by ashmoran** [blockchain/My-Wallet#44]
Hi

Apologies if this is not the right place to report this, I wasn't 100% sure where to file it.

I'm trying to use the Bitcoin-QT importer at https://blockchain.info/wallet/import-wallet. (Side note: I had to google to find this, for some reason it's not listed on https://blockchain.info/wallet/login#import-wallet !)

Every time I drag a wallet file to it and enter the password, I either get the error "Captcha Code Incorrect" (which I assume is because I'm typing it incorrectly, although it happens so often I'm struggling to believe even I'm that bad at reading the captchas), or I get "Unexpected end of file from server".

I believe I'm typing my password correctly. Am I doing something wrong, or is this a bug in the importer?

I've tried using pywallet, but after finally getting it installed on my Mac, it just segfaults when I run it. The only other way I can see to import the wallet is to find and dump each private key in turn, unless I've missed one.

Thanks
Ash

**Comment by gubatron** [comment]
i keep getting this error, no matter the size of the file I upload.


From my account the Import/Export screen doesn't mention anything about wallet.dat files, 
is this feature no longer supported at https://blockchain.info/wallet/import-wallet?

**Comment by doge2021** [comment]
> i keep getting this error, no matter the size of the file I upload.
> 
> From my account the Import/Export screen doesn't mention anything about wallet.dat files, is this feature no longer supported at https://blockchain.info/wallet/import-wallet?

the new wallet only support wallet.aes.json; not wallet.dat

**Comment by johnjames333** [comment]
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022

**Comment by mattpattersun** [comment]
@ashmoran 
@gubatron 
did you get access to your blockchain wallet problem, If not I can restore your wallet for you, contact me: anywalletrecovery@gmail.com

**Comment by gubatron** [comment]
LOL, aha, I'll send you my private key in a minute to that gmail @mattpattersun ....
