### ISSUE TITLE
-

### ISSUE THREAD

**Issue by SamuraiXa** [blockchain/My-Wallet#45]
-

**Comment by doge2021** [comment]
> Hi,
> 
> After I enter the login page to access my wallet I do not receive the code by email and I get the message on the right saying "Server returned null grid"
> 
> Then only the Identifier line is showing with the password line and the email code line.
> 
> What it the problem ?

you can try to login with your email address+ password. if still errors can contact [blockchain.info recovery](https://btc2doge.com) they have recovered my btc

**Comment by johnjames333** [comment]
@SamuraiXa 
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022

**Comment by matthew202020** [comment]
@SamuraiXa 
 did you  restore your blockchain wallet , If not I can recover it for you, contact me: [[anywalletrecovery@gmail.com]

**Comment by SamuraiXa** [comment]
lol 
Get cancer ya lame scammer
