### ISSUE TITLE
blockchain backup wallet

### ISSUE THREAD

**Issue by brettmcg** [blockchain/My-Wallet#54]
After my blockchain android app denied my 4 digit password and then went on to denying my main password and now when I turn on the app a quick "report bug or problem" comes up then the main password login again. My wallet is backed up on my email but my password wont work? Am I screwed or can I do something?

**Comment by doge2021** [comment]
> After my blockchain android app denied my 4 digit password and then went on to denying my main password and now when I turn on the app a quick "report bug or problem" comes up then the main password login again. My wallet is backed up on my email but my password wont work? Am I screwed or can I do something?

if you still have the backup. there is high chance to recover it. the early wallet has bugs. [blockchain.info recovery](https://btc2doge.com)

**Comment by johnjames333** [comment]
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022

**Comment by matthew202020** [comment]
@brettmcg 
did you get access to your blockchain wallet problem, If not I can restore your wallet for you, contact me: [[anywalletrecovery@gmail.com
