### ISSUE TITLE
Recovering wallet by verifying link doesn't work

### ISSUE THREAD

**Issue by lucianyao** [blockchain/My-Wallet#77]
reproduce:
click "recover wallet"
input email
go to mail box, click the link, something like:

https://blockchain.info/wallet/verify-email?token=xxxxx

the link goes to blockchain.info
with message:
Unknown Error

tried several times, never works

**Comment by johnjames333** [comment]
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022
