### ISSUE TITLE
Error getting wallet balance

### ISSUE THREAD

**Issue by rhaegar4815** [blockchain/My-Wallet#86]
Identifier: 851aa550-16e6-4885-9d40-d11e8f8df221

Page shows Error getting wallet balance and my BTC amount is 0 (which is incorrect).

**Comment by johnjames333** [comment]
I just read your problem with your blockchain wallet.
and if you still has problem I can crack it. my fee is 20%. you can find my contact details on my profile
or you can send me message in telegram: @viladmir2022
